project:
  type: website

website:
  title: "Notes from a data janitor"
  site-url: https://github.com/damarals/blog
  repo-url: https://damarals.github.io/blog/
  open-graph: true
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/damarals
      - icon: twitter
        href: https://twitter.com/damarals_
format:
  html:
    theme: light.scss
    css: styles.css
    monofont: "Victor Mono"
