project:
  type: website
  output-dir: docs

website:
  title: "Notes from a data hacker"
  site-url: https://damarals.github.io/blog
  repo-url: https://github.com/damarals/blog
  open-graph: true
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/damarals
      - icon: twitter
        href: https://twitter.com/damarals_
format:
  html:
    theme: light.scss
    css: styles.css
    monofont: "Victor Mono"
