project:
  type: website

website:
  title: "blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/damarals
      - icon: twitter
        href: https://twitter.com/damarals_
format:
  html:
    theme: litera
    css: styles.css



